version: '3.8'

services:
  api:
    container_name: shopper
    image: node:20.15.1-slim
    restart: always
    tty: true
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: '/usr/app'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${PORT}
    command: >
      sh -c "npm install &&
      npm run build &&
      npx prisma generate &&
      npx prisma migrate dev &&
      npm run start:prod"
  db:
    container_name: shopper-db
    image: postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}