services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - meterAI-network
  api:
    container_name: api-meterAI
    image: node:18.18
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    working_dir: '/usr/src/app'
    env_file:
      - .env
    command: >
      sh -c "npm install &&
      npx prisma generate &&
      npx prisma migrate dev --name init &&
      npm run start:dev"
    networks: 
      - meterAI-network
networks:
  meterAI-network:
    name: meterAI-network
    external: true
    driver: bridge